name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest Tistory blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://tistory-rss-proxy.chanho1228-362.workers.dev/"
          max_post_count: 5
          comment_tag_name: "TISTORY"
          template: "<tr><td>$date</td><td><a href='$url'>$title</a></td></tr>"
          date_format: "ddd, mmm dd yyyy HH:MM"
          commit_message: "Update README with latest Tistory posts"
